name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  go:
    name: Golang CI
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
        go_version:
          - "1.19"
    steps:
      - uses: actions/checkout@v3
        name: Cloning repository
      - uses: actions/setup-go@v4
        name: Installing Go ${{ matrix.go_version }}
        with:
          go-version: ${{ matrix.go_version }}
      - name: Building project
        run: go build -race -v -o=staticgovanityurls .
      - name: Testing project
        run: go test
      - name: Formatting project
        run: goimports -e -d -l .
  # TODO: doc:
